### ISSUE TITLE
下下来代码未做任何变更，直接运行出现listing directory，显示js文件目录

### ISSUE THREAD

**Issue by gitzhan** [huanglinqing123/Compose_Web_Wasm#1]
运行效果
![image](https://github.com/huanglinqing123/Compose_Web_Wasm/assets/24983630/42ae2a79-8898-4980-9063-f1de4b1f15e3)
idea 
![image](https://github.com/huanglinqing123/Compose_Web_Wasm/assets/24983630/a7ecebc4-a4f8-4c0d-bb9d-1e2ffa382dcf)

**Comment by huanglinqing123** [comment]
> 运行效果 ![image](https://user-images.githubusercontent.com/24983630/239963857-42ae2a79-8898-4980-9063-f1de4b1f15e3.png) idea ![image](https://user-images.githubusercontent.com/24983630/239964337-a7ecebc4-a4f8-4c0d-bb9d-1e2ffa382dcf.png)

你好，运行时Run的种类应该选择wasmRun,而不是截图中的jsBrowserDEvelopmentRun

**Comment by gitzhan** [comment]
厉害了！使用wasmRun就可以了。前两天加了个通宵，这才有时间验证。
